### PR TITLE
Add Parameter Types (versions 2 of the library)

### PR DESCRIPTION
**Pull request by Jean85**
This is a split of #24, to make it more clear what the end result of the new tags will be, so we can vote on it.

### CODE REVIEW

**Comment by Jean85** [comment]
@crell / @navarr, should we merge #13 in here too? WDYT?

**Comment by Crell** [comment]
I think that's reasonable. Modulo making sure we don't break Symfony again. :sweat_smile:

**Comment by Jean85** [comment]
The only issue that that kind of upgrade creates is the same that we encountered in https://github.com/php-fig/container/issues/33 as you said, breaking Symfony. That issue is a bug only on PHP < 7.4 and since we're requiring 8 here, we would be good to go!

**Review by navarr — APPROVED** [review]

**Comment by Geolim4** [comment]
Hello,

https://github.com/php-fig/fig-standards/pull/1252 has been merged, can this MR be merged too ?

(As well as https://github.com/php-fig/simple-cache/pull/24 ?)

**Comment by Jean85** [comment]
Vote has passed: https://groups.google.com/g/php-fig/c/DJ8ysB1JV4Y
PSR changes are merged: https://github.com/php-fig/fig-standards/pull/1252

Releasing this as 2.0.0 now.

**Pull request merged**
