### PR TITLE
Add a CacheAwareInterface and its CacheAwareTrait.

### PR DESCRIPTION
**Pull request by drupol**
Hello,

Just like in [Psr/Log](https://github.com/php-fig/log), this pull request adds a CacheAwareInterface and a simple CacheAwareTrait.

### CODE REVIEW

**Comment by spotman** [comment]
:+1: for merging that! It will help to follow DRY principle.

**Comment by drupol** [comment]
Coool ! Good news :-)

Ping @dragoonis

**Comment by XedinUnknown** [comment]
Adding `CacheAwareInterface` is IMHO a good idea, and I generally follow this pattern in Dhii standards as well. I also have started to add factory interfaces, i.e. `CacheFactoryInterface#make($config): CacheInterface`. I base mine on [`FactoryInterface`][], but of course I understand very well that PSR interfaces will not base themselves on mine - and they shouldn't. Still, having a `FactoryInterface` could be a great thing for FIG.

At the same time, `CacheAwareTrait` is not a good idea in this package, because this is a standrds package, and a trait is implementation. That said, it doesn't mean that there shouldn't be such a trait. What I usually do is split my stuff into layers: interface, abstract, base, concrete. Not all levels are always necessary, but something like `CacheAwareTrait` would live in the abstract layer, such as my [`ContainerAwareTrait`][].

My organisation seeks to be a flexible and fast-paced complement to FIG, and I would happily add and maintain centralized implementations of things like `CacheAwareTrait`. Please take a look at my [standards][Dhii], especially the PHP ones.

#### P.S.
Looked at the `CacheAwareTrait`. Generally, mutators should not be part of the standard, IMHO, because usually consuming something does not involve mutating it. Of course there are cases where this is not so, but overall I think that standards should aim for immutability. I follow this pattern:

- `*AwareInterface` exposes a getter, i.e. `get*()`.
- Something that has a `setCache()` would be called `SetCacheCapableInterface`.
- For traits, the getter and setter would be together in the same `*AwareTrait`. This is because my traits declare only protected methods in 99% of the cases, and it is OK. Another reason is to avoid property declaration conflicts during composition, as the "aware" trait also needs to declare the corresponding protected property.

[Dhii]: https://github.com/Dhii/dhii
[`FactoryInterface`]: https://github.com/Dhii/factory-interface/blob/develop/src/FactoryInterface.php
[`ContainerAwareTrait`]: https://github.com/Dhii/data-container-abstract/blob/develop/src/ContainerAwareTrait.php

**Comment by dragoonis** [comment]
Hey everyone!

Adding traits and aware's are probably not something we're going to include into this standard. I'd be happy with a framework-level implementation around this, so they can inject their implementation of CacheInterface into an object, when it has the trait or the aware interface on it.

Symfony and other libraries are already having a nice time with this standard, and I don't see a huge community push behind adding this, so for that reason I'm going to say: leave it to the framework vendors to add their own injection strategy in, and keep this standard clean.

I hope this made sense, and sorry to disappoint some folks, who wanted this out of the box.

**Comment by XedinUnknown** [comment]
A framework-level implementation is by definition not interop. The whole point of having a `CacheAwareInterface` or `CacheFactoryInterface` (I'm especially interested in the latter) is so that modules can be interoperable. See [this thread][1], and also [`CachePoolFactoryInterface`][].

[1]: https://twitter.com/XedinUnknown/status/1250027347794964481
[`CachePoolFactoryInterface`]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePoolFactoryInterface.php

**Comment by Jean85** [comment]
This does not belong here. It should only live under a `simple-cache-util` repo.

Feel free to enquire with the CC, on Discord or on the mailing list to push this forward.

**Pull request closed without merging**
